name: Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Клонируем репозиторий
    - uses: actions/checkout@v1
    # Устанавливаем NodeJS
    - uses: actions/setup-node@v4
    # Устанавливаем все зависимости
    - run: npm i
    # Запускаем тесты
    - name: run tests
      run: npx jest