name: Tests

on: 
  - push
  - pull_request

env:
  CI: true

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      # Node versions list
      matrix:
        node-version: [20.x]

    steps:
    # Клонируем репозиторий
    - uses: actions/checkout@v4
    # Step's name
    - name: Use Node.js ${{ matrix.node-version }}
    # Устанавливаем NodeJS
    - uses: actions/setup-node@v4
    # Устанавливаем все зависимости
    - run: npm install
    # Запускаем тесты
    - name: run tests
      run: make test
    # Проверяем линтером
    - run: make lint